require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VersioningsController do

  # This should return the minimal set of attributes required to create a valid
  # Versioning. As you add validations to Versioning, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "version" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VersioningsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all versionings as @versionings" do
      versioning = Versioning.create! valid_attributes
      get :index, {}, valid_session
      assigns(:versionings).should eq([versioning])
    end
  end

  describe "GET show" do
    it "assigns the requested versioning as @versioning" do
      versioning = Versioning.create! valid_attributes
      get :show, {:id => versioning.to_param}, valid_session
      assigns(:versioning).should eq(versioning)
    end
  end

  describe "GET new" do
    it "assigns a new versioning as @versioning" do
      get :new, {}, valid_session
      assigns(:versioning).should be_a_new(Versioning)
    end
  end

  describe "GET edit" do
    it "assigns the requested versioning as @versioning" do
      versioning = Versioning.create! valid_attributes
      get :edit, {:id => versioning.to_param}, valid_session
      assigns(:versioning).should eq(versioning)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Versioning" do
        expect {
          post :create, {:versioning => valid_attributes}, valid_session
        }.to change(Versioning, :count).by(1)
      end

      it "assigns a newly created versioning as @versioning" do
        post :create, {:versioning => valid_attributes}, valid_session
        assigns(:versioning).should be_a(Versioning)
        assigns(:versioning).should be_persisted
      end

      it "redirects to the created versioning" do
        post :create, {:versioning => valid_attributes}, valid_session
        response.should redirect_to(Versioning.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved versioning as @versioning" do
        # Trigger the behavior that occurs when invalid params are submitted
        Versioning.any_instance.stub(:save).and_return(false)
        post :create, {:versioning => { "version" => "invalid value" }}, valid_session
        assigns(:versioning).should be_a_new(Versioning)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Versioning.any_instance.stub(:save).and_return(false)
        post :create, {:versioning => { "version" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested versioning" do
        versioning = Versioning.create! valid_attributes
        # Assuming there are no other versionings in the database, this
        # specifies that the Versioning created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Versioning.any_instance.should_receive(:update).with({ "version" => "MyString" })
        put :update, {:id => versioning.to_param, :versioning => { "version" => "MyString" }}, valid_session
      end

      it "assigns the requested versioning as @versioning" do
        versioning = Versioning.create! valid_attributes
        put :update, {:id => versioning.to_param, :versioning => valid_attributes}, valid_session
        assigns(:versioning).should eq(versioning)
      end

      it "redirects to the versioning" do
        versioning = Versioning.create! valid_attributes
        put :update, {:id => versioning.to_param, :versioning => valid_attributes}, valid_session
        response.should redirect_to(versioning)
      end
    end

    describe "with invalid params" do
      it "assigns the versioning as @versioning" do
        versioning = Versioning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Versioning.any_instance.stub(:save).and_return(false)
        put :update, {:id => versioning.to_param, :versioning => { "version" => "invalid value" }}, valid_session
        assigns(:versioning).should eq(versioning)
      end

      it "re-renders the 'edit' template" do
        versioning = Versioning.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Versioning.any_instance.stub(:save).and_return(false)
        put :update, {:id => versioning.to_param, :versioning => { "version" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested versioning" do
      versioning = Versioning.create! valid_attributes
      expect {
        delete :destroy, {:id => versioning.to_param}, valid_session
      }.to change(Versioning, :count).by(-1)
    end

    it "redirects to the versionings list" do
      versioning = Versioning.create! valid_attributes
      delete :destroy, {:id => versioning.to_param}, valid_session
      response.should redirect_to(versionings_url)
    end
  end

end
