version_status: [{label: 'working', code: 0}, {label: 'message', code: 1}, {label: 'must_update', code: 2}]
version_check_http_label: 'Version-Check'
version_default_message: 'Your current application version is outdated. Please update!'